2022-04-02 15:46:35.789 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 15:46:47.079 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 15:57:55.611 | ERROR    | db_requests:update_record:162 - Ошибка при работе с SQLite
2022-04-02 16:02:37.656 | ERROR    | db_requests:update_record:162 - Ошибка при работе с SQLite
2022-04-02 16:07:06.815 | DEBUG    | __main__:check_old_data:118 - (1, 'ATOMUSDT', 30.5, 10700.71, '2022-04-02 15:47:05.236706', '1999-01-01 00:00:00.000000') 0.004262295081967182)
2022-04-02 16:07:35.542 | DEBUG    | __main__:check_old_data:118 - (13, 'EOSUSDT', 2.863, 129836.8, '2022-04-02 15:47:19.824836', '1999-01-01 00:00:00.000000') 0.004889975550122161)
2022-04-02 16:08:03.571 | DEBUG    | __main__:check_old_data:118 - (20, 'ADAUSDT', 1.165, 545083.4, '2022-04-02 15:47:27.669006', '1999-01-01 00:00:00.000000') 0.017167381974249052)
2022-04-02 16:08:21.610 | DEBUG    | __main__:check_old_data:118 - (37, 'XRPUSDT', 0.85, 1128110.0, '2022-04-02 15:47:30.062445', '1999-01-01 00:00:00.000000') 0.00741176470588234)
2022-04-02 16:08:23.734 | DEBUG    | __main__:check_old_data:118 - (38, 'XRPUSDT', 0.8519, 363399.0, '2022-04-02 15:47:30.069452', '1999-01-01 00:00:00.000000') 0.009625542904096673)
2022-04-02 16:12:59.819 | DEBUG    | __main__:check_old_data:118 - (2, 'ATOMUSDT', 31.0, 14575.97, '2022-04-02 15:47:05.242705', '2022-04-02 16:07:07.461900') 0.012580645161290316)
2022-04-02 16:20:11.241 | DEBUG    | __main__:check_old_data:118 - (16, 'MATICUSDT', 1.75, 208409.3, '2022-04-02 15:47:24.758738', '2022-04-02 16:13:10.622845') 0.01942857142857146)
2022-04-02 16:20:49.521 | DEBUG    | __main__:check_old_data:118 - (53, 'AVAXUSDT', 105.0, 9512.41, '2022-04-02 15:47:40.530106', '2022-04-02 16:09:58.316548') 0.017238095238095275)
2022-04-02 16:27:52.138 | DEBUG    | __main__:check_old_data:118 - (430, 'AVAXUSDT', 104.0, 3320.35, '2022-04-02 15:55:47.731819', '1999-01-01 00:00:00.000000') 0.006826923076923008)
2022-04-02 16:27:58.595 | ERROR    | db_requests:update_record:162 - Ошибка при работе с SQLite
2022-04-02 16:29:36.927 | DEBUG    | __main__:check_old_data:118 - (29, 'ADAUSDT', 1.2, 683587.3, '2022-04-02 16:04:49.849708', '1999-01-01 00:00:00.000000') 0.01083333333333325)
2022-04-02 16:40:25.503 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 16:40:44.222 | DEBUG    | __main__:check_old_data:118 - (16, 'MATICUSDT', 1.75, 210463.5, '2022-04-02 15:47:24.758738', '2022-04-02 16:29:24.302280') 0.01657142857142857)
2022-04-02 16:44:16.340 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 16:45:21.789 | ERROR    | __main__:check_old_data:123 - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-04-02 16:45:35.480 | ERROR    | __main__:polling:138 - HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2022-04-02 16:47:33.311 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 16:48:48.836 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 16:52:08.088 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 16:52:15.764 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 17:05:45.960 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 17:07:16.950 | DEBUG    | __main__:<module>:17 - Start script
2022-04-02 17:11:13.971 | DEBUG    | __main__:<module>:17 - Start script
